<?php

$sLangName = "English";

$aLang = array(
    'charset'                                          => 'UTF-8',

    'SHOP_MODULE_GROUP_styla_api'                      => 'API Settings',
    'SHOP_MODULE_GROUP_styla_feed'                     => 'Feed Settings',
    'SHOP_MODULE_styla_api_key'                        => 'API Key',
    'SHOP_MODULE_styla_feed_basedir'                   => 'Base directory',
    'SHOP_MODULE_styla_page_size'                      => 'Page size',
    'SHOP_MODULE_styla_image_attribute'                => 'Image Attribute',
    'SHOP_MODULE_styla_image_width'                    => 'Image Width',
    'SHOP_MODULE_styla_image_height'                   => 'Image Height',
    'SHOP_MODULE_styla_extra_attributes'               => 'Extra Attributes',
    'SHOP_MODULE_styla_feed_cache_ttl'                 => 'Cache-lifetime (seconds)',

    'SHOP_MODULE_GROUP_styla_general'                  => 'Styla Settings',
    'SHOP_MODULE_styla_username'                       => 'Styla/Amazine Username',
    'SHOP_MODULE_styla_prophet_url'                    => 'JS Snippet URL',
    'SHOP_MODULE_styla_seo_basedir'                    => 'Base directory',
    'SHOP_MODULE_styla_seo_cache_ttl'                  => 'Cache-lifetime (seconds)',
    'SHOP_MODULE_styla_seo_magazin_title'              => 'Magazine page title contains shop pre- and suffix',
    'SHOP_MODULE_styla_seo_server'                     => 'SEO server URL',
    'SHOP_MODULE_styla_api_url'                        => 'API domain URL',
    'SHOP_MODULE_styla_feed_search_cols'               => 'Fields Styla uses for searching',
    'SHOP_MODULE_styla_feed_search_subcategories'      => 'Expand product search to sub categories of the searched categories',
    'HELP_SHOP_MODULE_styla_feed_search_subcategories' => 'If this setting is active all subcategories (and their subcategories) of the searched category will also be searched<br><b>Attention: Activating this setting can lead to performance losses and a slower search (< 10 sec) on systems with a high article or subcategory amount</b>',
    'SHOP_MODULE_styla_feed_sorting'                   => 'Sort variants in the given order. <br>OXSORT will be used if this setting is empty.<br>Single values have to be separated by ; <br>Example: S;L;XL',
    'SHOP_MODULE_styla_feed_brand'                     => 'Show brand in product feed',
    'SHOP_MODULE_styla_feed_brand_none'                => 'None',
    'SHOP_MODULE_styla_feed_brand_oxmanufacturer'      => 'Manufacturer (oxmanufacturer)',
    'SHOP_MODULE_styla_feed_brand_oxvendor'            => 'Vendor (oxvendor)',
    'SHOP_MODULE_styla_feed_vat_showlabel'             => 'Show VAT inscription in product feed',
    'SHOP_MODULE_styla_feed_show_variant_urls'         => 'Use variant URLs',
    'SHOP_MODULE_styla_feed_no_empty_categories'       => 'Don\'t show empty categories in feed',

    'STYLA'                                            => 'Styla',
    'Styla_Paths'                                      => 'Styla',
    'Styla_Paths_new'                                  => 'New path for Styla',
    'Styla_PathsList'                                  => 'Path settings',
    'Styla_PathsTab'                                   => 'Settings',
    'STYLA_PATHS_PATH'                                 => 'Path',
    'STYLA_PATHS_PATHHELP'                             => 'Config for the styla path',
    'STYLA_PATHS_USER'                                 => 'User',
    'STYLA_PATHS_USERHELP'                             => 'Config of the user',
    'STYLA_PATHS_LANG'                                 => 'Language',
    'STYLA_PATHS_LANGHELP'                             => 'Language Config',
    'STYLA_PATHS_HOME'                                 => 'Home',
    'STYLA_PATHS_HOMEHELP'                             => 'Should the style content been displayed on the shop landing-page?',
    'STYLA_PATHS_BASEDIR'                              => 'Basedirectory',
    'STYLA_PATHS_BASEDIRHELP'                          => 'Is the directory a base directory and has sub-pages?',
    
);
